[tool.poetry]
name = "dataanalytics"
version = "0.1.0"
description = ""
authors = ["Tobias2408 <Tobiaspo@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
kaggle = "^1.6.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
