name: Test and Upload Python Package

on:
  push:
    branches:
      - main
      - preprocess_ai
  release:
    types: [published]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: ankane/pgvector
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd preprocess_ai
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify directory structure
      run: |
        cd preprocess_ai
        ls -al
        ls -al DataPreparation
        ls -al DataPreparation/DataCleaner
        ls -al DataPreparation/DataReduction
        ls -al DataPreparation/DataTransformation
        ls -al tests

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/preprocess_ai" >> $GITHUB_ENV

    - name: Set TEST_DB_URL environment variable
      run: echo "TEST_DB_URL=postgresql://testuser:testpassword@localhost:5432/testdb" >> $GITHUB_ENV

    - name: Run tests
      run: |
        cd preprocess_ai
        python -m unittest discover -s tests -p "Test*.py"

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd preprocess_ai
        python -m pip install --upgrade pip
        pip install build twine toml

    - name: Increment version
      run: |
        cd preprocess_ai
        python increment_version.py

    - name: Commit updated version
      run: |
        cd preprocess_ai
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add pyproject.toml setup.py
        git commit -m "Increment version"
        git push

    - name: Build package
      run: |
        cd preprocess_ai
        python -m build

    - name: List files in dist directory
      run: |
        cd preprocess_ai
        ls -al dist

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: dist
