name: Test and Upload Python Package

on:
  push:
    branches:
      - main
      - preprocess_ai
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: ankane/pgvector
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Uninstall global SimpleAI_Image if exists
      run: pip uninstall -y SimpleAI_Image || true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas sqlalchemy pgvector matplotlib tensorflow scikit-learn openai

    - name: Verify directory structure
      run: |
        ls -al
        ls -al preprocess_ai
        ls -al preprocess_ai/tests

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/preprocess_ai" >> $GITHUB_ENV

    - name: Set TEST_DB_URL environment variable
      run: echo "TEST_DB_URL=postgresql://testuser:testpassword@localhost:5432/testdb" >> $GITHUB_ENV

    - name: Run tests
      run: |
        cd preprocess_ai
        python -m unittest discover -s tests -p "Test*.py"

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: |
        cd preprocess_ai
        python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        cd preprocess_ai
        twine upload dist/*
