name: Run tests

on:
  push:
    branches:
      - main
      - SimpleAI_Image

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: ankane/pgvector
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Uninstall global SimpleAI_Image if exists
      run: pip uninstall -y SimpleAI_Image || true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r SimpleAI_Image/requirements.txt
        pip install -r SimpleAI_Image/requirements-test.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/SimpleAI_Image" >> $GITHUB_ENV

    - name: Set TEST_DB_URL environment variable
      run: echo "TEST_DB_URL=postgresql://testuser:testpassword@localhost:5432/testdb" >> $GITHUB_ENV

    - name: Run tests
      run: python -m unittest discover -s SimpleAI_Image/tests -p "Test*.py"
